server.port=8080

spring.application.name=GraphQL

spring.graphql.path=/graphql
spring.graphql.schema.locations=classpath:graphql/**
spring.graphql.schema.file-extensions=.graphql
spring.graphql.graphiql.enabled=true

spring.datasource.url=jdbc:h2:mem:test_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update